/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import com.sun.javafx.scene.SceneHelper;
import java.awt.Color;
import java.net.Socket;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private GuiDataDemoThs sk;
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setResizable(false);
        pnMenu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbExit = new javax.swing.JLabel();
        lbAbout = new javax.swing.JLabel();
        lbPlayOnline = new javax.swing.JLabel();
        lbPvP = new javax.swing.JLabel();
        lbPvC = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName(""); // NOI18N
        setUndecorated(true);
        setResizable(false);

        pnMenu.setLayout(null);
        pnMenu.add(jLabel8);
        jLabel8.setBounds(960, 10, 32, 32);

        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu/thoat.png"))); // NOI18N
        lbExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbExitMouseReleased(evt);
            }
        });
        pnMenu.add(lbExit);
        lbExit.setBounds(50, 540, 344, 105);

        lbAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu/thong_tin.png"))); // NOI18N
        lbAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAboutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbAboutMouseReleased(evt);
            }
        });
        pnMenu.add(lbAbout);
        lbAbout.setBounds(50, 420, 344, 105);

        lbPlayOnline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlayOnline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu/choi_online_fix.png"))); // NOI18N
        lbPlayOnline.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbPlayOnline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbPlayOnlineMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbPlayOnlineMouseReleased(evt);
            }
        });
        pnMenu.add(lbPlayOnline);
        lbPlayOnline.setBounds(50, 300, 344, 105);

        lbPvP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPvP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu/choi_2_nguoi.png"))); // NOI18N
        lbPvP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbPvP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbPvPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbPvPMouseReleased(evt);
            }
        });
        pnMenu.add(lbPvP);
        lbPvP.setBounds(50, 180, 344, 105);

        lbPvC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPvC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu/choi_vs_may.png"))); // NOI18N
        lbPvC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbPvC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbPvCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbPvCMouseReleased(evt);
            }
        });
        pnMenu.add(lbPvC);
        lbPvC.setBounds(50, 60, 344, 105);

        lbTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu/Caro_fix.png"))); // NOI18N
        pnMenu.add(lbTitle);
        lbTitle.setBounds(430, 40, 407, 318);

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Background.png"))); // NOI18N
        pnMenu.add(bg);
        bg.setBounds(0, 0, 1000, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbPvCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPvCMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Menu/choi_vs_may_press.png"));
        lbPvC.setIcon(II);
    }//GEN-LAST:event_lbPvCMousePressed

    private void lbPvCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPvCMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Menu/choi_vs_may.png"));
        lbPvC.setIcon(II);
        int x = evt.getX();
        int y = evt.getY();      
        if ((x > 0) && (x < (lbPvC.getWidth())) && (y > 0) && (y < (lbPvC.getHeight()))) {
            PvC pc = new PvC(this);
            pc.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lbPvCMouseReleased

    private void lbPvPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPvPMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Menu/choi_2_nguoi_press.png"));
        lbPvP.setIcon(II);
    }//GEN-LAST:event_lbPvPMousePressed

    private void lbPvPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPvPMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Menu/choi_2_nguoi.png"));
        lbPvP.setIcon(II);
        int x = evt.getX();
        int y = evt.getY();      
        if ((x > 0) && (x < (lbPvP.getWidth())) && (y > 0) && (y < (lbPvP.getHeight()))) {
            PvP pc = new PvP(this);
            pc.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_lbPvPMouseReleased

    private void lbPlayOnlineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayOnlineMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Menu/choi_online_press.png"));
        lbPlayOnline.setIcon(II);
    }//GEN-LAST:event_lbPlayOnlineMousePressed

    private void lbPlayOnlineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayOnlineMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Menu/choi_online_fix.png"));
        lbPlayOnline.setIcon(II);
        int x = evt.getX();
        int y = evt.getY();      
        if ((x > 0) && (x < (lbPlayOnline.getWidth())) && (y > 0) && (y < (lbPlayOnline.getHeight()))) {
            if(this.getSk()!=null){//neu da ton tai socket thi vo thang game
                new PvP(this).show();
            }else{//chua ton tai thi vao dang nhap
                Login lg = new Login(this, true,this);
                lg.setVisible(true);
            }
        }
    }//GEN-LAST:event_lbPlayOnlineMouseReleased

    public GuiDataDemoThs getSk() {
        return sk;
    }

    public void setSk(GuiDataDemoThs sk) {
        this.sk = sk;
    }

    private void lbAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAboutMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Menu/thong_tin_press.png"));
        lbAbout.setIcon(II);
    }//GEN-LAST:event_lbAboutMousePressed

    private void lbAboutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAboutMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Menu/thong_tin.png"));
        lbAbout.setIcon(II);
    }//GEN-LAST:event_lbAboutMouseReleased

    private void lbExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Menu/thoat_press.png"));
        lbExit.setIcon(II);
    }//GEN-LAST:event_lbExitMousePressed

    private void lbExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Menu/thoat.png"));
        lbExit.setIcon(II);
        int x = evt.getX();
        int y = evt.getY();      
        if ((x > 0) && (x < (lbExit.getWidth())) && (y > 0) && (y < (lbExit.getHeight()))) {
            Exit ex = new Exit(this, true);
            ex.setVisible(true);
        }
    }//GEN-LAST:event_lbExitMouseReleased

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        // TODO add your handling code here:
        Exit ex = new Exit(this, true);
        ex.setVisible(true);
    }//GEN-LAST:event_lbExitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbAbout;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbPlayOnline;
    private javax.swing.JLabel lbPvC;
    private javax.swing.JLabel lbPvP;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnMenu;
    // End of variables declaration//GEN-END:variables
}
