/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class PvC extends javax.swing.JFrame {

    /**
     * Creates new form PvC
     */
    Menu mn;
    private Graphics grs;
    int giay;
    int _CheDoChoi;

    public int getCheDoChoi() {
        return _CheDoChoi;
    }

    public void setCheDoChoi(int _CheDoChoi) {
        this._CheDoChoi = _CheDoChoi;
    }
    

    public PvC(Menu mn) {
        initComponents();
        grs = pnBoard.getGraphics();
        _CheDoChoi=1;
        pnBoard.StartPvsP(grs);
        setLocationRelativeTo(null);
        this.mn = mn;
    }
    
    public PvC(Menu mn,int a){
        initComponents();
        grs = pnBoard.getGraphics();
        _CheDoChoi=2;
        pnBoard.StartPvcC(grs);
        setLocationRelativeTo(null);
        this.mn = mn;
    }

    public void setGiay(int giay) {
        this.giay = giay;
    }

    public int getGiay() {
        return giay;
    }

    public void setTime() {
        if (getGiay() < 0) {
            JOptionPane.showMessageDialog(null, " time over ");
            pnBoard.setSanSang(false);
        } else {
            switch (getGiay()) {
                case 15:
                    ImageIcon II15 = new ImageIcon(getClass().getResource("/Image/Time/15.png"));
                    lbtime.setIcon(II15);
                    break;
                case 14:
                    ImageIcon II14 = new ImageIcon(getClass().getResource("/Image/Time/14.png"));
                    lbtime.setIcon(II14);
                    break;
                case 13:
                    ImageIcon II13 = new ImageIcon(getClass().getResource("/Image/Time/13.png"));
                    lbtime.setIcon(II13);
                    break;
                case 12:
                    ImageIcon II12 = new ImageIcon(getClass().getResource("/Image/Time/12.png"));
                    lbtime.setIcon(II12);
                    break;
                case 11:
                    ImageIcon II11 = new ImageIcon(getClass().getResource("/Image/Time/11.png"));
                    lbtime.setIcon(II11);
                    break;
                case 10:
                    ImageIcon II10 = new ImageIcon(getClass().getResource("/Image/Time/10.png"));
                    lbtime.setIcon(II10);
                    break;
                case 9:
                    ImageIcon II9 = new ImageIcon(getClass().getResource("/Image/Time/9.png"));
                    lbtime.setIcon(II9);
                    break;
                case 8:
                    ImageIcon II8 = new ImageIcon(getClass().getResource("/Image/Time/8.png"));
                    lbtime.setIcon(II8);
                    break;
                case 7:
                    ImageIcon II7 = new ImageIcon(getClass().getResource("/Image/Time/7.png"));
                    lbtime.setIcon(II7);
                    break;
                case 6:
                    ImageIcon II6 = new ImageIcon(getClass().getResource("/Image/Time/6.png"));
                    lbtime.setIcon(II6);
                    break;
                case 5:
                    ImageIcon II5 = new ImageIcon(getClass().getResource("/Image/Time/5.png"));
                    lbtime.setIcon(II5);
                    break;
                case 4:
                    ImageIcon II4 = new ImageIcon(getClass().getResource("/Image/Time/4.png"));
                    lbtime.setIcon(II4);
                    break;
                case 3:
                    ImageIcon II3 = new ImageIcon(getClass().getResource("/Image/Time/3.png"));
                    lbtime.setIcon(II3);
                    break;
                case 2:
                    ImageIcon II2 = new ImageIcon(getClass().getResource("/Image/Time/2.png"));
                    lbtime.setIcon(II2);
                    break;
                case 1:
                    ImageIcon II1 = new ImageIcon(getClass().getResource("/Image/Time/1.png"));
                    lbtime.setIcon(II1);
                    break;
                case 0:
                    ImageIcon II0 = new ImageIcon(getClass().getResource("/Image/Time/0.png"));
                    lbtime.setIcon(II0);
                    break;
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPvC = new javax.swing.JPanel();
        lbExit = new javax.swing.JLabel();
        pnBoard = new demo.Carochess();
        lbUndo = new javax.swing.JLabel();
        lbLose = new javax.swing.JLabel();
        lbtime = new javax.swing.JLabel();
        lbPlay = new javax.swing.JLabel();
        lbBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnPvC.setPreferredSize(new java.awt.Dimension(1000, 700));
        pnPvC.setLayout(null);

        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Board/thoat.png"))); // NOI18N
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbExitMouseReleased(evt);
            }
        });
        pnPvC.add(lbExit);
        lbExit.setBounds(869, 611, 60, 64);

        pnBoard.setPreferredSize(new java.awt.Dimension(501, 501));
        pnBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnBoardMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnBoardLayout = new javax.swing.GroupLayout(pnBoard);
        pnBoard.setLayout(pnBoardLayout);
        pnBoardLayout.setHorizontalGroup(
            pnBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );
        pnBoardLayout.setVerticalGroup(
            pnBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        pnPvC.add(pnBoard);
        pnBoard.setBounds(441, 48, 501, 501);

        lbUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Board/Undo.png"))); // NOI18N
        lbUndo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbUndoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbUndoMouseReleased(evt);
            }
        });
        pnPvC.add(lbUndo);
        lbUndo.setBounds(551, 612, 65, 65);

        lbLose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Board/Lose.png"))); // NOI18N
        lbLose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLoseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbLoseMouseReleased(evt);
            }
        });
        pnPvC.add(lbLose);
        lbLose.setBounds(772, 612, 65, 65);
        pnPvC.add(lbtime);
        lbtime.setBounds(652, 611, 82, 82);

        lbPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Board/Play.png"))); // NOI18N
        lbPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbPlayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbPlayMouseReleased(evt);
            }
        });
        pnPvC.add(lbPlay);
        lbPlay.setBounds(454, 611, 65, 65);

        lbBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Board/PvC.png"))); // NOI18N
        pnPvC.add(lbBg);
        lbBg.setBounds(0, 0, 1000, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnPvC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnPvC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void lbExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Board/thoat_press.png"));
        lbExit.setIcon(II);
    }//GEN-LAST:event_lbExitMousePressed

    private void lbExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Board/thoat.png"));
        lbExit.setIcon(II);
        int x = evt.getX();
        int y = evt.getY();
        if ((x > 0) && (x < (lbExit.getWidth())) && (y > 0) && (y < (lbExit.getHeight()))) {
            dispose();
            this.mn.setVisible(true);
            pnBoard.countTimeClose();
        }
    }//GEN-LAST:event_lbExitMouseReleased

    private void pnBoardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBoardMouseReleased
        if (pnBoard.time != null) {
            pnBoard.countTimeClose();
        }
        if (pnBoard.DanhCo(evt.getX(), evt.getY(), grs)) {
            pnBoard.countTimeOpen(this);
            if (pnBoard.KiemTraChienThang()) {
                pnBoard.ThongBao();
            } else {
                if (_CheDoChoi == 2) {
                    pnBoard.KhoiDongComputer(grs);
                    if (pnBoard.KiemTraChienThang()) {
                        pnBoard.ThongBao();
                    }
                }
            }
        }
    }//GEN-LAST:event_pnBoardMouseReleased

    private void lbPlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Board/Play_press.png"));
        lbPlay.setIcon(II);
    }//GEN-LAST:event_lbPlayMousePressed

    private void lbPlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Board/Play.png"));
        lbPlay.setIcon(II);
        int x = evt.getX();
        int y = evt.getY();
        if ((x > 0) && (x < (lbPlay.getWidth())) && (y > 0) && (y < (lbPlay.getHeight()))) {
            if(_CheDoChoi == 2){
                pnBoard.StartPvcC(grs);
                this.setGiay(16);
            }
            else pnBoard.StartPvsP(grs);
        }
    }//GEN-LAST:event_lbPlayMouseReleased

    private void lbUndoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUndoMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Board/Undo_press.png"));
        lbUndo.setIcon(II);
    }//GEN-LAST:event_lbUndoMousePressed

    private void lbUndoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUndoMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Board/Undo.png"));
        lbUndo.setIcon(II);
        int x = evt.getX();
        int y = evt.getY();
        if ((x > 0) && (x < (lbUndo.getWidth())) && (y > 0) && (y < (lbUndo.getHeight()))) {
            this.setGiay(16);
            if(_CheDoChoi==1)
                pnBoard.UndoPvsP(grs);
            else pnBoard.UndoPvsC(grs);
        }
    }//GEN-LAST:event_lbUndoMouseReleased

    private void lbLoseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLoseMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Board/Lose_press.png"));
        lbLose.setIcon(II);
    }//GEN-LAST:event_lbLoseMousePressed

    private void lbLoseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLoseMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Board/Lose.png"));
        lbLose.setIcon(II);
        pnBoard.setKetThuc(Carochess.KetThuc.COM);
        pnBoard.ThongBao();
    }//GEN-LAST:event_lbLoseMouseReleased

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbBg;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbLose;
    private javax.swing.JLabel lbPlay;
    private javax.swing.JLabel lbUndo;
    private javax.swing.JLabel lbtime;
    private demo.Carochess pnBoard;
    private javax.swing.JPanel pnPvC;
    // End of variables declaration//GEN-END:variables
}
